Refactor Python 3
loco-3d/multicontact-locomotion-planning pull request #29
Opened 2020-01-21 17:57 UTC by pFernbach

Fix previous refactoring (see discussions in https://github.com/loco-3d/multicontact-locomotion-planning/pull/28)

2020-01-21 18:00 UTC, nim65s approved these changes

2020-01-21 18:26 UTC, nim65s requested changes

2020-01-21 18:26 UTC, nim65s commented on scripts/mlp/centroidal/topt.py
> +                   ):  # values for id = 0 are aready the last point in the trajectory computed by genSplinesForPhase
This comment should go on its own line

2020-01-21 18:26 UTC, nim65s commented on scripts/mlp/centroidal/topt.py
> +    #FIXME
I think there is a missing space after the `#`, but yapf should have added it.

2020-01-21 18:26 UTC, nim65s commented on scripts/mlp/contact_sequence/manually_defined/flat_floor.py
> +    placement)  # add a new contact phase, with a contact created for the right feet at the given placement
This comment should go on its own line

2020-01-21 18:26 UTC, nim65s commented on scripts/mlp/contact_sequence/sl1m.py
> +            "INSTALL_HPP_DIR"] + "/share/talos-rbprm/com_inequalities/feet_quasi_flat/talos_COM_constraints_in_LF_effector_frame_REDUCED.obj"
still too long, as well as the 2 others below.

2020-01-21 18:26 UTC, nim65s commented on scripts/mlp/demo_configs/common_talos.py
> +).T  #Reference config used by the wholeBody script, may be different than the one used by the planning (default value is the same as planning)
This comment should go on its own line

2020-01-21 18:26 UTC, nim65s commented on scripts/mlp/demo_configs/talos_bauzil_with_stairs.py
> +).T  #Reference config used by the wholeBody script, may be different than the one used by the planning (default value is the same as planning)
This comment should go on its own line

2020-01-21 18:26 UTC, nim65s commented on scripts/mlp/demo_configs/talos_lp_complex.py
> +).T  #Reference config used by the wholeBody script, may be different than the one used by the planning (default value is the same as planning)
This comment should go on its own line

2020-01-21 18:26 UTC, nim65s commented on scripts/mlp/demo_configs/talos_lp_maze.py
> +).T  #Reference config used by the wholeBody script, may be different than the one used by the planning (default value is the same as planning)
This comment should go on its own line

2020-01-21 18:26 UTC, nim65s commented on scripts/mlp/demo_configs/talos_lp_slalom.py
> +).T  #Reference config used by the wholeBody script, may be different than the one used by the planning (default value is the same as planning)
This comment should go on its own line

2020-01-21 18:26 UTC, nim65s commented on scripts/mlp/demo_configs/talos_mazeEas.py
> +).T  #Reference config used by the wholeBody script, may be different than the one used by the planning (default value is the same as planning)
This comment should go on its own line

2020-01-21 18:26 UTC, nim65s commented on scripts/mlp/demo_configs/talos_mazeEas_oriented.py
> +).T  #Reference config used by the wholeBody script, may be different than the one used by the planning (default value is the same as planning)
… you get the idea x)

2020-01-21 18:26 UTC, nim65s commented on scripts/mlp/demo_configs/talos_navBauzil.py
> +).T  #Reference config used by the wholeBody script, may be different than the one used by the planning (default value is the same as planning)
same here

2020-01-21 18:26 UTC, nim65s commented on scripts/mlp/end_effector/bezier_constrained.py
> +            -1]  # ratio between the imposed time of the bezier curve (t) and the "time" (a pseudo distance) of the solution of the rrt
here too

2020-01-21 18:26 UTC, nim65s commented on scripts/mlp/utils/util.py
> +    ) == 1:  # depend if eigenpy.switchToNumpyArray() have been called, FIXME : there should be a better way to check this
and here

2020-01-21 18:26 UTC, nim65s commented on scripts/mlp/utils/wholebody_result.py
> +                             ])  # timing vector (1 x N ) (time at each discretized point, from t=0 to t=dt*(N-1))
same in this file

2020-01-21 18:26 UTC, nim65s commented on scripts/mlp/wholebody/tsid_invdyn.py
> +        )  # plot inside this file, as we have access to the real Bezier object and not only the discretization stored in 'res' struct
also here

2020-01-22 09:57 UTC, pFernbach commented
Thanks for the review, latest commit apply the changes requested.

2020-01-22 10:02 UTC, nim65s approved these changes
That's looking better, thanks :)

2020-01-22 10:06 UTC, merged